server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: emtech-logistics
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/emtech_logistics}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
  
  cache:
    type: redis
    redis:
      time-to-live: 600000
  
  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: ${JWT_SECRET:EmTechLogistics2025SuperSecretKeyForJWTTokenGenerationAndValidation}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

logging:
  level:
    com.emtech.logistics: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_LOG_LEVEL:WARN}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/emtech-logistics.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  ai:
    enabled: true
    model: gpt-3.5-turbo
    api-key: ${OPENAI_API_KEY:}
  
  audit:
    enabled: true
    retention-days: 365
  
  email:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    from: ${EMAIL_FROM:noreply@emtechlogistics.com}
    
  notifications:
    low-stock-threshold: 10
    expiry-warning-days: 30
    
  backup:
    enabled: true
    schedule: "0 0 2 * * ?" # Daily at 2 AM
    retention-days: 30
